steps:
    -
        name: gcr.io/cloud-builders/docker
        args:
            - build
            - '-t'
            - 'gcr.io/$PROJECT_ID/luxspace:cloudbuild-$BRANCH_NAME-$SHORT_SHA'
            - .
    -
    
   
        name: gcr.io/cloud-builders/docker
        args:
            - tag
            - 'gcr.io/$PROJECT_ID/luxspace:cloudbuild-$BRANCH_NAME-$SHORT_SHA'
            - 'gcr.io/$PROJECT_ID/luxspace:cloudbuild-$BRANCH_NAME-latest'
            
    -
        name: 'gcr.io/cloud-builders/docker'
        args:
            - push 
            - 'gcr.io/$PROJECT_ID/luxspace:cloudbuild-$BRANCH_NAME-$SHORT_SHA'
    -
            
        name: 'gcr.io/cloud-builders/docker'
        args:
            - push 
            - 'gcr.io/$PROJECT_ID/luxspace:cloudbuild-$BRANCH_NAME-latest'
    -
        name : 'gcr.io/cloud-builders/gcloud'
        args :
            - run
            - deploy
            - 'luxspace'
            - '--image'
            - 'gcr.io/$PROJECT_ID/luxspace:cloudbuild-$BRANCH_NAME-$SHORT_SHA'
            - '--region'
            - 'asia-southeast1'
            - '--platform'
            - 'managed'
            - '--allow-unauthenticated'
            
images:
          - 'gcr.io/$PROJECT_ID/crud-op:cloudbuild-$BRANCH_NAME-$SHORT_SHA'
          - 'gcr.io/$PROJECT_ID/crud-op:cloudbuild-$BRANCH_NAME-latest'